name: CI/CD Medical Chatbot

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Stop old container
        run: |
          docker stop medical-chatbot || true
          docker rm medical-chatbot || true

      - name: Build Docker image
        run: |
          docker build -t medical-chatbot .

      - name: Run container
        run: |
          docker run -d \
          -p 8080:8080 \
          --name medical-chatbot \
          -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
          -e PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }} \
          medical-chatbot